CREATE PROCEDURE [elt].[spCopySrcToRaw]
    @process_run_date DATE, @process_run_id INT
AS

BEGIN
    WITH CTE
    AS (SELECT DISTINCT
        ELT.VWMETADATA.SYSTEMNAME,
        ELT.VWMETADATA.SYSTEMTYPE,
        ELT.VWMETADATA.SCHEMANAME,
        ELT.VWMETADATA.ENTITYNAME
        FROM ELT.VWMETADATA
    )

    SELECT
        CTE.SYSTEMNAME AS SOURCE_SYSTEM_NAME,
        CTE.ENTITYNAME AS SOURCE_ENTITY_NAME,
        ELT.[METADATATABLES].INCREMENTCOLUMNNAME AS SOURCE_ENTITY_INCREMENT_COLUMN,
        [elt].[fnCreateQuery](
            CTE.SYSTEMNAME,
            CTE.SYSTEMTYPE,
            CTE.SCHEMANAME,
            CTE.ENTITYNAME,
            @process_run_id,
            ELT.[METADATATABLES].SOURCEQUERY,
            ELT.[METADATATABLES].INCREMENTCOLUMNNAME,
            @process_run_date,
            ELT.[METADATATABLES].INCREMENTRANGE,
            CAST(ELT.[METADATATABLES].LASTINCREMENT AS DATE),
            CAST(ELT.[METADATATABLES].LASTINCREMENT AS TIME(3))
        ) AS SOURCE_ENTITY_QUERY,
        [elt].[fnCreateEntityStructure](
            CTE.SYSTEMNAME, CTE.SCHEMANAME, CTE.ENTITYNAME
        ) AS SOURCE_ENTITY_STRUCTURE,
        [elt].[fnCreateStagingFileName](
            CTE.ENTITYNAME,
            CTE.SCHEMANAME,
            ELT.[METADATATABLES].INCREMENTCOLUMNNAME,
            @process_run_date,
            ELT.[METADATATABLES].INCREMENTRANGE
        ) AS SINK_ENTITY_FILE_NAME,
        [elt].[fnCreateStagingFolderPath](
            CTE.SYSTEMNAME, @process_run_date
        ) AS SINK_ENTITY_FOLDER_PATH,
        [elt].[fnCreateEntityStructure](
            CTE.SYSTEMNAME, CTE.SCHEMANAME, CTE.ENTITYNAME
        ) AS SINK_ENTITY_STRUCTURE,
        [elt].[fnCreateEntityTranslator](
            CTE.SYSTEMNAME, CTE.SCHEMANAME, CTE.ENTITYNAME
        ) AS SOURCE_SINK_MAPPING
    FROM ELT.[MetadataTables]
    INNER JOIN CTE ON CTE.SYSTEMNAME = ELT.[METADATATABLES].SYSTEMNAME
        AND CTE.ENTITYNAME = ELT.[METADATATABLES].ENTITYNAME
        AND CTE.SCHEMANAME = ELT.[METADATATABLES].SCHEMANAME
    WHERE ELT.[METADATATABLES].COPYTORAW = 1
        AND ELT.[METADATATABLES].ISACTIVE = 1
    --AND vcm.SystemName = @system_name
    ORDER BY CTE.SYSTEMNAME ASC
END;
