CREATE PROCEDURE [elt].[spSystemStorageDays] AS

SELECT
    [ELT].[SYSTEMSTORAGEDAYS].SYSTEMNAME,
    [ELT].[SYSTEMSTORAGEDAYS].STORAGEDAYS * -1 AS STORAGEDAYS,
    CONCAT('raw/', [ELT].[SYSTEMSTORAGEDAYS].SYSTEMNAME, '/') AS FOLDERPATH
FROM [elt].[SystemStorageDays]
INNER JOIN ELT.METADATASYSTEM
    ON [ELT].[SYSTEMSTORAGEDAYS].SYSTEMNAME = ELT.METADATASYSTEM.SYSTEMNAME
        AND ELT.METADATASYSTEM.ACTIVE = 1
--where SystemName = @system_name
