TRUNCATE TABLE [reference].[country]
GO
INSERT INTO [reference].[country]
    ([country]  ,[region_NL],[region_DR] ,[region_OW],[region_OF],[subregion_OF])
VALUES
     ('Afghanistan',NULL,NULL,NULL,'Middle east','North Europe')
    ,('Åland Islands','EUR','EUR','EUR',NULL,'Middle East')
    ,('Albania','EUR','EUR','EUR','East Europe','South Europe')
    ,('Algeria','EUR','EUR','EUR','South Europe','North West Africa')
    ,('American Samoa','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Andorra','EUR','EUR','EUR','South Europe','South Europe')
    ,('Angola','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Anguilla','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Antarctica','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Antigua and Barbuda','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Argentina','Americas','Americas','Americas','South America','South America')
    ,('Armenia','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Aruba','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Australia','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Austria','EUR','EUR','EUR','North Europe','North Europe')
    ,('Azerbaijan','EUR','EEAF','EEAF','Middle east','Caspian Sea')
    ,('Bahamas','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Bahrain','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Bangladesh','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Barbados','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Belarus','EUR','EUR','EUR','North Europe','North Europe')
    ,('Belgium','Netherlands',NULL,NULL,'North Europe','North Europe')
    ,('Belize','Americas','Americas','Americas','North and Central America','Central America')
    ,('Benin','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Bermuda','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Bhutan','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Bolivia, Plurinational State of','Americas','Americas','Americas','South America','South America')
    ,('Bonaire, Sint Eustatius and Saba','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Bosnia and Herzegovina','EUR','EUR','EUR','East Europe','South Europe')
    ,('Botswana','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Bouvet Island','EEAF','EEAF','EEAF',NULL,'SSA-South East')
    ,('Brazil','Americas','Americas','Americas','South America',NULL)
    ,('British Indian Ocean Territory','MEAA','MEAA','MEAA',NULL,'West Asia')
    ,('British Virgin Islands',NULL,NULL,NULL,'North and Central America','Caribbean')
    ,('Brunei Darussalam','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Bulgaria','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Burkina Faso','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Burundi','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Cabo Verde',NULL,NULL,NULL,'Africa','SSA-West')
    ,('Cambodia','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Cameroon','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Canada','EUR','EUR','EUR','North and Central America','Canada')
    ,('Cape Verde','EEAF','EEAF','EEAF',NULL,NULL)
    ,('Canary islands',NULL,NULL,NULL,'Africa','SSA-West')
    ,('Caribbean Netherlands',NULL,NULL,NULL,'North and Central America','Caribbean')
    ,('Cayman Islands','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Central African Republic','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Chad','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Chile','Americas','Americas','Americas','South America','South America')
    ,('China','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Christmas Island','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('Cocos (Keeling) Islands','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('Colombia','Americas','Americas','Americas','South America','Colombia')
    ,('Comoros','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Congo','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Congo, the Democratic Republic of the','EEAF','EEAF','EEAF',NULL,NULL)
    ,('Cook Islands','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Costa Rica','Americas','Americas','Americas','North and Central America','Central America')
    ,('Côte d''Ivoire','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Croatia','EUR','EUR','EUR','South Europe','South Europe')
    ,('Cuba','Americas','Americas','Americas','North and Central America','Central America')
    ,('Curaçao','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Cyprus','EUR','EUR','EUR','South Europe','South Europe')
    ,('Czech Republic','EUR','EUR','EUR','North Europe','North Europe')
    ,('Denmark','EUR','EUR','EUR','North Europe','North Europe')
    ,('Djibouti','MEAA','MEAA','MEAA','Africa','North East Africa')
    ,('Dominica','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Dominican Republic','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Ecuador','Americas','Americas','Americas','South America','Caribbean')
    ,('Egypt','MEAA','MEAA','MEAA','Middle east','North East Africa')
    ,('El Salvador','Americas','Americas','Americas','North and Central America','Central America')
    ,('Equatorial Guinea','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Eritrea','MEAA','MEAA','MEAA','Africa','North East Africa')
    ,('Estonia','EUR','EUR','EUR','North Europe','North Europe')
    ,('Eswatini',NULL,NULL,NULL,'Africa','SSA-West')
    ,('Ethiopia','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Falkland Islands (Malvinas)','Americas','Americas','Americas',NULL,NULL)
    ,('Faeroe Islands',NULL,NULL,NULL,'North Europe','North Europe')
    ,('Falkland Islands',NULL,NULL,NULL,'South America','South America')
    ,('Faroe Islands','EUR','EUR','EUR','North Europe','North Europe')
    ,('Fiji','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Finland','EUR','EUR','EUR','North Europe','North Europe')
    ,('France','EUR','EUR','EUR','South Europe','South Europe')
    ,('French Guiana','Americas','Americas','Americas','South America','Central America')
    ,('French Polynesia','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('French Southern Territories','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('Gabon','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Gambia','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Georgia','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Germany','EUR','EUR','EUR','North Europe','Germany')
    ,('Ghana','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Gibraltar','EUR','EUR','EUR','South Europe','South Europe')
    ,('Greece','EUR','EUR','EUR','South Europe','South Europe')
    ,('Greenland','EUR','EUR','EUR','North and Central America','North Europe')
    ,('Grenada','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Guadeloupe','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Guam','MEAA','MEAA','MEAA','Asia','Australia')
    ,('Guatemala','Americas','Americas','Americas','North and Central America','Central America')
    ,('Guernsey','EUR','EUR','EUR','North Europe','West Europe')
    ,('Guinea','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Guinea-Bissau','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Guyana','Americas','Americas','Americas','South America','Central America')
    ,('Haiti','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Heard Island and McDonald Mcdonald Islands','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('Holy See',NULL,NULL,NULL,'South Europe','South Europe')
    ,('Honduras','Americas','Americas','Americas','North and Central America','Central America')
    ,('Hong Kong','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Hungary','EUR','EEAF','EEAF','North Europe','Black Sea')
    ,('Iceland','EUR','EUR','EUR','North Europe','North Europe')
    ,('India','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Indonesia','MEAA','MEAA','MEAA','Asia','Indonesia')
    ,('Iran','EUR','EEAF','EEAF','Middle east','Middle East')
    ,('Iran, Islamic Republic of','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Iraq','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Ireland','EUR','EUR','EUR','North Europe','West Europe')
    ,('Isle of Man','EUR','EUR','EUR','North Europe','West Europe')
    ,('Israel','EUR','EUR','EUR','South Europe','North West Africa')
    ,('Italy','EUR','EUR','EUR','South Europe','South Europe')
    ,('Jamaica','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Japan','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Jersey','EUR','EUR','EUR','North Europe','West Europe')
    ,('Jordan','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Kazakhstan','EUR','EEAF','EEAF','East Europe','Caspian Sea')
    ,('Kenya','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Kiribati','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Korea, Democratic People''s Republic of','MEAA','MEAA','MEAA',NULL,NULL)
    ,('Korea, Republic of','MEAA','MEAA','MEAA',NULL,NULL)
    ,('Kuwait','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Kyrgyzstan','EUR','EEAF','EEAF','Asia','Caspian Sea')
    ,('Lao People''s Democratic Republic','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Latvia','EUR','EUR','EUR','North Europe','North Europe')
    ,('Lebanon','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Lesotho','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Liberia','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Libya','MEAA','MEAA','MEAA','South Europe','North East Africa')
    ,('Liechtenstein','EUR','EUR','EUR','North Europe','North Europe')
    ,('Lithuania','EUR','EUR','EUR','North Europe','North Europe')
    ,('Luxembourg','EUR','EUR','EUR','North Europe','South Europe')
    ,('Macao','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Macedonia, the Former Yugoslav Republic of','EUR','EEAF','EEAF',NULL,'Black Sea')
    ,('Madagascar','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Malawi','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Malaysia','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Maldives','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Mali','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Malta','EUR','EUR','EUR','South Europe','South Europe')
    ,('Marshall Islands','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Martinique','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Mauritania','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Mauritius','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Mayotte','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Mexico','Americas','Americas','Americas','North and Central America','Mexico')
    ,('Micronesia, Federated States of','MEAA','MEAA','MEAA','Australia & Oceania','East Asia')
    ,('Moldova, Republic of','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Monaco','EUR','EUR','EUR','North Europe','South Europe')
    ,('Mongolia','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Montenegro','EUR','EUR','EUR','East Europe','South Europe')
    ,('Montserrat','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Morocco','EUR','EUR','EUR','South Europe','North West Africa')
    ,('Mozambique','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Myanmar','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Namibia','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Nauru','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Nepal','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Netherlands','Netherlands',NULL,NULL,'North Europe','West Europe')
    ,('Netherlands Antilles','Americas','Americas','Americas','Australia & Oceania','Australia')
    ,('New Caledonia','MEAA','MEAA','MEAA',NULL,NULL)
    ,('New Zealand','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Nicaragua','Americas','Americas','Americas','North and Central America','Central America')
    ,('Niger','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Nigeria','EEAF','EEAF','EEAF','Africa','Nigeria')
    ,('Niue','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Norfolk Island','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('North Korea',NULL,NULL,NULL,'Asia','East Asia')
    ,('North Macedonia',NULL,NULL,NULL,'East Europe','Black Sea')
    ,('Northern Mariana Islands','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Norway','EUR','EUR','EUR','North Europe','North Europe')
    ,('Oman','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Pakistan','MEAA','MEAA','MEAA','Asia','Middle East')
    ,('Palau','MEAA','MEAA','MEAA','Asia','Australia')
    ,('Palestine, State of','MEAA','MEAA','MEAA','South Europe','Middle East')
    ,('Panama','Americas','Americas','Americas','North and Central America','Central America')
    ,('Papua New Guinea','MEAA','MEAA','MEAA','Asia','Australia')
    ,('Paraguay','Americas','Americas','Americas','South America','South America')
    ,('Peru','Americas','Americas','Americas','South America','Central America')
    ,('Philippines','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Pitcairn','MEAA','MEAA','MEAA',NULL,'Australia')
    ,('Poland','EUR','EUR','EUR','North Europe','North Europe')
    ,('Portugal','EUR','EUR','EUR','South Europe','South Europe')
    ,('Puerto Rico','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Qatar','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Republic of the congo',NULL,NULL,NULL,'Africa','SSA-South East')
    ,('Réunion','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Romania','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Russia','MEAA','MEAA','MEAA','East Europe','Russia')
    ,('Russian Federation','EUR','EEAF','EEAF',NULL,NULL)
    ,('Rwanda','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Saint Barthélemy','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Saint Helena, Ascension and Tristan da Cunha','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Saint Kitts and Nevis','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Saint Lucia','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Saint Martin (French part)','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Saint Pierre and Miquelon','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Saint Vincent and the Grenadines','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Samoa','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('San Marino','EUR','EUR','EUR','South Europe','South Europe')
    ,('Sao Tome and Principe','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Saudi Arabia','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Senegal','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Serbia','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Seychelles','EEAF','EEAF','EEAF','Asia','SSA-South East')
    ,('Sierra Leone','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Singapore','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Sint Maarten (Dutch part)','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Slovakia','EUR','EUR','EUR','North Europe','North Europe')
    ,('Slovenia','EUR','EUR','EUR','South Europe','South Europe')
    ,('Solomon Islands','MEAA','MEAA','MEAA','Asia','Australia')
    ,('Somalia','MEAA','MEAA','MEAA','Africa','North East Africa')
    ,('South Africa','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('South Georgia and the South Sandwich Islands','Americas','Americas','Americas',NULL,NULL)
    ,('South Korea',NULL,'MEAA','MEAA','Asia','East Asia')
    ,('South Sudan','MEAA','MEAA','MEAA','Africa','North East Africa')
    ,('Spain','EUR','EUR','EUR','South Europe','South Europe')
    ,('Sri Lanka','MEAA','MEAA','MEAA','Asia','West Asia')
    ,('Sudan','MEAA','MEAA','MEAA','Africa','North East Africa')
    ,('Suriname','Americas','Americas','Americas','South America','Central America')
    ,('Svalbard and Jan Mayen','EUR','EUR','EUR',NULL,'North Europe')
    ,('Swaziland','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Sweden','EUR','EUR','EUR','North Europe','North Europe')
    ,('Switzerland','EUR','EUR','EUR','North Europe','North Europe')
    ,('Syrian Arab Republic','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Taiwan','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Taiwan R.O.C.','MEAA','MEAA','MEAA',NULL,NULL)
    ,('Tajikistan','EUR','EEAF','EEAF','Asia','Caspian Sea')
    ,('Tanzania',NULL,'EEAF','EEAF','Africa','SSA-South East')
    ,('Tanzania, United Republic of','EEAF','EEAF','EEAF',NULL,NULL)
    ,('Thailand','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Timor-Leste','MEAA','MEAA','MEAA','Asia','Indonesia')
    ,('Togo','EEAF','EEAF','EEAF','Africa','SSA-West')
    ,('Tokelau','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Tonga','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Trinidad and Tobago','Americas','Americas','Americas','South America','Caribbean')
    ,('Tunisia','EUR','EUR','EUR','South Europe','North West Africa')
    ,('Turkey','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('Turkmenistan','EUR','EEAF','EEAF','East Europe','Caspian Sea')
    ,('Turks and Caicos Islands','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Tuvalu','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Uganda','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Ukraine','EUR','EEAF','EEAF','East Europe','Black Sea')
    ,('United Arab Emirates','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('United Kingdom','EUR','EUR','EUR','North Europe','West Europe')
    ,('United States','Americas','Americas','Americas','North and Central America','Central America')
    ,('United States Minor Outlying Islands','MEAA','MEAA','MEAA',NULL,NULL)
    ,('Uruguay','Americas','Americas','Americas','South America','South America')
    ,('Uzbekistan','EUR','EEAF','EEAF','East Europe','Caspian Sea')
    ,('Vanuatu','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Venezuela, Bolivarian Republic of','Americas','Americas','Americas','South America','Central America')
    ,('Viet Nam','MEAA','MEAA','MEAA','Asia','East Asia')
    ,('Virgin Islands, British','Americas','Americas','Americas','North and Central America','Caribbean')
    ,('Virgin Islands, U.S.','Americas','Americas','Americas',NULL,NULL)
    ,('Wallis and Futuna','MEAA','MEAA','MEAA','Australia & Oceania','Australia')
    ,('Western Sahara','EEAF','EEAF','EEAF',NULL,'SSA-West')
    ,('Yemen','MEAA','MEAA','MEAA','Middle east','Middle East')
    ,('Zambia','EEAF','EEAF','EEAF','Africa','SSA-South East')
    ,('Zimbabwe','EEAF','EEAF','EEAF','Africa','SSA-South East')
GO