name: GitHub Actions for SQL database | Parallelly build and release using matrix stratergy

on:
  ## uses main branch and specific path
  push:
    branches:
      - feature/init_database
    paths:
      - database/**

jobs:
  build:
  ## A matrix can be used to iterate the actions over several inputs parallelly
    strategy:
      matrix:
        name: [dwh, mdb]
       
  ## msbuild for m10 framework doesn't build on windows-latest
    runs-on: windows-2019
    steps:
    - name: Checkout this repository | Required to build projects
      uses: actions/checkout@v1
    
    - name: Setup MSBuild | Required to build db projects
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    
    - name: Build database project | Build the projects from the sln file
      run: msbuild database\sqldb.sln /p:Configuration=Release
    
    - name: Publish build artifacts for ${{ matrix.name }} | Upload dacpac files to workflow run
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.name }}
        path: ${{ github.workspace }}\database\${{ matrix.name }}\bin\Release\

  ## Release on the development environment
  release:
    needs: build
    environment: Development
    strategy:
      matrix:
        name: [dwh, mdb]
    runs-on: windows-latest

    steps:
    - name: Download the artifact for ${{ matrix.name }} | Download dacpac files on the windows runner
      uses: actions/download-artifact@v2.0.6
      with:
        name: ${{ matrix.name }}

    - name: Use credentials | Log in into Azure
      uses: azure/login@v1
      with:
        creds: '{
                  "clientId":"${{ vars.SP_ID }}",
                  "clientSecret":"${{ secrets.SP_SECRET }}",
                  "subscriptionId":"${{ vars.SUBSCRIPTION_ID }}",
                  "tenantId":"${{ vars.TENANT_ID }}"
                }'

  ## Conditioning helps to specify data catalogs/target databases where the dacpac file needs to be deployed
  ## As the the database folder names is same as the target dbs [dwh, mdb], this action is not required atm
    # - uses: haya14busa/action-cond@v1
    #   id: condition
    #   with:
    #     cond: ${{ matrix.name == 'dwh' }}
    #     if_true: "test2"
    #     if_false: "testdbtf"
    
  ## Store the connection string in the KV. Make sure the SP can access the secrets in KV
  ## As we are using Github secrets and variables, this action is not required atm
    # - name: log in keyvault
    #   uses: Azure/get-keyvault-secrets@v1
    #   with: 
    #     keyvault: "pos-kv"
    #     secrets: 'dwh, mdb'
    #   id: connection_string
   
  ## There is no need of dynamic firewall setting when you allow Azure services to access the server by default.
    - name: Publish ${{ matrix.name }} | Publishes dacpac files to target dbs
      uses: azure/sql-action@v2
      with:
  ## connection string via SP is bugged, track: https://github.com/Azure/sql-action/issues/137
        connection-string: 'Server=tcp:${{ vars.DB_SERVER }}.database.windows.net,1433;Initial Catalog=${{ matrix.name }};Authentication=${{ vars.AUTH_TYPE }};User ID=${{ vars.SP_ID }};Password=${{ secrets.SP_SECRET }};'
        path: '${{ github.workspace }}\${{ matrix.name }}.dacpac'
        action: 'Publish'

    - name: Logout from Azure
      run: |
         az logout